# Site settings
title:       Dokter's Notes
author:      Masha Safina
description: ":rocket: A responsive Jekyll theme based on my personal internet site"
baseurl:     "/"
url:         "https://dokterw.github.io"

# Social Links
email:            safe@masha.space
twitter_username: dokterw
github_username:  dokterw

# Build settings
markdown: kramdown
permalink: pretty
