# Site settings
title:       Dokter's Notes
author:      Dokter Waldijk
description: "Privacy, cryptography, security, code & rants."
baseurl:     ""
url:         "https://dokterw.github.io"

# Social Links
#email:            safe@masha.space
twitter_username: dokterw
github_username:  dokterw

# Build settings
markdown: kramdown
permalink: pretty
